apiVersion: v1
kind: Secret
metadata:
  name: rocket-webhook
  namespace: flux-system
data:
  address: rocketchat-rocketchat.flux-system.svc.cluster.local
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: rocket
  namespace: flux-system
spec:
  type: rocket
  secretRef:
    name: rocket-webhook
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  summary: "cluster addons"
  eventMetadata:
    env: "staging"
    cluster: "my-cluster"
    region: "us-east-2"
  providerRef:
    name: rocket
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
---
