apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ghcr-io
  namespace: flux-system
spec:
  interval: 5m0s
  image: ghcr.io/kyverno/manifests/kyverno:v1.13.4
  certSecretRef:
    name: ghcr-io-tls
