---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: error-team
  namespace: error-team
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: errorr-team-auth
  url: https://github.com/org/audi-new-team
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: error-team
  namespace: error-team
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: error-team
  sourceRef:
    kind: GitRepository
    name: new-team
