apiVersion: v1
kind: Service
metadata:
  namespace: flux-system
  name: rocketchat-extern
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app.kubernetes.io/name: rocketchat
