apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  releaseName: rocketchat
  chart:
    spec:
      chart: rocketchat-server/rocketchat
      version: '6.24.x'
      sourceRef:
        kind: HelmRepository
        name: rocketchat
  values:
    mongodb:
      auth:
        passwords:
          - rocketchat
        rootPassword: rocketchatroot
  interval: 5m
