apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  releaseName: rocketchat
  chart:
    spec:
      chart: rocketchat
      version: '6.25.x'
      sourceRef:
        kind: HelmRepository
        name: rocketchat
  values:
    mongodb:
      auth:
        passwords:
          - rocketchat
        rootPassword: rocketchatroot
    extraVolumes:
      - name: etc-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
      - name: share-certs
        hostPath:
          path: /usr/share/ca-certificates
          type: Directory
    extraVolumeMounts:
      - mountPath: /etc/ssl/certs
        name: etc-certs
        readOnly: true
      - mountPath: /usr/share/ca-certificates
        name: share-certs
        readOnly: true
  interval: 5m
